# Generated by Django 5.1.1 on 2024-09-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('solicitor', 'Solicitor'), ('barrister', 'Barrister'), ('judge', 'Judge')], max_length=10)),
                ('case_summary', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
